### ISSUE TITLE
Unify postgres setup

### ISSUE THREAD

**Issue by Pinwheeler** [Parrit/Parrit#37]
We need to make only one required database and only one required user. Both the database name and the user name need to be parrit and not pivotal

**Comment by thebucknerlife** [comment]
We are working on it.

**Comment by Pinwheeler** [comment]
To clarify, I'd prefer the user to not have to have two databases, I'd prefer them to only need one database and it to be called parrit and I'd prefer the username that is required to be 'parrit' as well

**Comment by jgreubel** [comment]
I've renamed the databases to:

local_parrit
local_parrit_test

Also removed the need for a username/password since these are only local databases (prod/stage still have passwords)

I still think it's better to have separate test/dev databases incase your tests conflict with your dev data, also if in the future we get e2e tests, it would be nice to be able to run the tests and still use the dev app without interfering with the test database.
