### ISSUE TITLE
app is down HTTP 502

### ISSUE THREAD

**Issue by santiagovm** [Parrit/Parrit#76]
https://parrit.io/ returns 502

**Comment by tkruse** [comment]
@Pinwheeler : Any insight about this?

**Comment by Pinwheeler** [comment]
@santiagovm @tkruse 

Hey all- sorry about the service interruptions. This is what happens when a small team side project moves server architectures. If y'all are interested in seeing more of what happens to be going wrong I would definitely love a hand.

We're running spring boot on a linux box through CoudFoundry and this most recent crash was due to `broken pipe`

I've been investigating and restarting and fixing as this crops up and appreciate your patience.

`java.io.IOException: Broken pipe `

**Comment by tkruse** [comment]
Could you post the full stacktrace?

**Comment by Pinwheeler** [comment]
https://gist.github.com/Pinwheeler/a14431d0a9397f76e1194ac98ee8452a

I'm not sure if that's the right logs exactly, that's what I get using `journalctl -xb -1 > log.txt` it looks the same as `journalctl -u parrit`

**Comment by Pinwheeler** [comment]
@tkruse I've switched over to the newest version of the webapp. It seems that things are more stable. We're monitoring this

**Comment by arthur-ms** [comment]
We're getting 502 errors again. Is it coming from the same issue?

**Comment by Pinwheeler** [comment]
@arthur-ms I don't believe so- it looks like this last one was caused by a null pointer loop causing a crash at some point. Unsure exactly, but looking into it as time allows. We should be back up and running at least :)

**Comment by andreasevers** [comment]
It appears the website is down.

**Comment by Pinwheeler** [comment]
@andreasevers 

thanks for alerting me to the issue.

Looks like our card for auto-renew on DNS expired. I've re-purchased the domain and Parrit should be back tomorrow.

**Comment by andreasevers** [comment]
Awesome! Pivotal FTW!

**Comment by Pinwheeler** [comment]
Closing this (longstanding) issue as it appears that the underlying site reliability issues have been solved and we probably want to track any additional issues separately.
