### ISSUE TITLE
Monthly Standup 1 - 3/3/21

### ISSUE THREAD

**Issue by cielzee** [Parrit/Parrit#87]
3/10/21 Agenda: 

- [x] Discuss monthly standup / format (working with collaborators)
- [x] Estimate creating a home page
- [x] Continue brainstorm on when to run pair recordings: HMW automatically record pairing history for a global user base?
- [x] New insights https://miro.com/app/board/o9J_ldkszAU=/
- [x] New faces (@8:30pm)
- [x] Backlog Reviews (Product in [GitHub](https://github.com/Parrit/Parrit/projects/3) / Engineering in [Tracker](https://www.pivotaltracker.com/n/projects/1504460))
- [x] Helps / Blockers
- [x] Discuss story about removing history over 30 days and dependencies https://www.pivotaltracker.com/story/show/176018739

Template Agenda: 
- New faces
- New insights
- Backlog Reviews
- Helps / Blockers
- Group Session

**Comment by cielzee** [comment]
Cat's help: Pair with Anthony to brush up on Front-End

**Comment by DarcieF** [comment]
**Comments / Notes:** 
- Monthly standup discussion: time is divided for @Pinwheeler wants to continue to work on Parrit is connecting 
- Might be fun to do a New Faces Plus (what brings you here?) - Add an icebreakers 
- Analytics story - because it is a single page webpage having trouble tracking clicks (something to keep in mind when rewriting the routers for the app) 
- Click events can usually have something in the javascript 
- Note: Tag manager is placing variables in the code and managed through a UI 
- Can't mess with the URLs too much because each page is hard coded for security - @moleske should know more 
- Home page estimate: there are a lot of services that do a snazzy single page site generators (in editor to set it up) - may be some free ones and definitely some paid ones - if we want to design something bespoke may take a little more time
- Adding new pages to the website itself is a little challenging / even adding to the end of the url parrit.io/landing (security layer that doesn't permit the server to create a page / CORS) @moleske 
- Could do a TLD eg: marketing.parrit.io - the right way to do it is the CORS 
- Automatic recording of pairs - MVP could be midnight GMT / we don't really record the timezone of where people are (could base off the browser timezone but would be more complicated as a next iteration)
- Need to add Hanchen to GitHub and Tracker

**Comment by DarcieF** [comment]
Hi @moleske :) your name came up in our community standup last night so I tagged you above in places where we had questions that only you can answer. Would love to connect if you can.
